### ISSUE TITLE
Feature Request Windows Support for Flutter SDK

### ISSUE THREAD

**Issue by markbreuss** [BugBattle/Android-SDK#10]
Hi there,

For the development of our web apps we are heavy bugbattle users (and fans 😉).
SInce we are currently developing a flutter deskop application (Windows) we would love to see the [flutter sdk](https://pub.dev/packages/bugbattle_sdk) expanded to more plattforms.

Cheers, 
Mark

**Comment by boehlerlukas** [comment]
Hey @markbreuss ,

thanks for your request. Our flutter SDK will be expanded to the Web pretty soon. Desktop will follow by the end of the year as this requires a lot more base work to be done :)

Best regards,
Lukas

**Comment by markbreuss** [comment]
Hi @boehlerlukas,

Great to hear!
thanks for the info!

Mark
