### ISSUE TITLE
App crashes with NullPointerException when takeScreenshot is invoked

### ISSUE THREAD

**Issue by SudoPlz** [BugBattle/Android-SDK#11]
Hey there friends,

We noticed a plethora of crashes (in production) originating from bug battle on Android, specifically when users try to invoke it with a screenshot.

Another stacktrace also includes the following error:
`Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
`

Here’s a stack trace:

```
java.lang.NullPointerException: 
  at bugbattle.io.bugbattle.ScreenshotTaker.openScreenshot (ScreenshotTaker.java:37)
  at bugbattle.io.bugbattle.ScreenshotTaker.takeScreenshot (ScreenshotTaker.java:33)
  at bugbattle.io.bugbattle.BBDetector.takeScreenshot (BBDetector.java:37)
  at bugbattle.io.bugbattle.ScreenshotGestureDetector.startBugReporting (ScreenshotGestureDetector.java:31)
  at bugbattle.io.bugbattle.ScreenshotGestureDetector.access$000 (ScreenshotGestureDetector.java:9)
  at bugbattle.io.bugbattle.ScreenshotGestureDetector$1.onChange (ScreenshotGestureDetector.java:43)
  at android.database.ContentObserver.onChange (ContentObserver.java:132)
  at bugbattle.io.bugbattle.ScreenshotGestureDetector$1.onChange (ScreenshotGestureDetector.java:48)
  at android.database.ContentObserver.onChange (ContentObserver.java:147)
  at android.database.ContentObserver$NotificationRunnable.run (ContentObserver.java:218)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7697)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:516)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

Are we doing something wrong, or is this just a bug?

We’re using: "react-native-bugbattle-sdk": "4.0.1”,
and this happens on [various devices and os versions](https://share.squarespace.com/jkuPRbbA)

Is that feature stable, or should we defer from using it?

Thank you

**Comment by boehlerlukas** [comment]
@SudoPlz thanks for reporting the issue. @niklasfessler will take care of this asap!

**Comment by niklasfessler** [comment]
Hey @SudoPlz,

im checking the bug. 

What react-native version are you using?
Lukas told me that you use rn bugbattle sdk 4.0.1?

Have you any alerts or modals on the screen? 

Is your source code public available?

Greetings Niklas

**Comment by SudoPlz** [comment]
Hi @niklasfessler 
I'm using `"react-native": "0.64.2",`

Not sure if the user saw any modals or alerts on the screen to be honest because those crash reports came automatically from real production devices, so I wasn't seeing what they were, but I assume not.

Our code is not publicly available I'm afraid.
Is there anything else I can do to help you?

Have you tested invoking with screenshot on a react-native app and it worked?

Thanks for your quick response

**Comment by SudoPlz** [comment]
I actually went through your new documents and noticed that you now suggest initializing your sdk with `BugBattle.autoConfigure` vs `BugBattle.initialize` that was used in the past.

We're still using `BugBattle.initialize`, could that be the root cause of the problem

**Comment by niklasfessler** [comment]
Yea it's working pretty well. The error indicates that we cant get the current activity of the app. We were testing on
"react-native": "0.63.4"

I will test it on a newer version. Just give me a sec. 

No thats not a problem, they are all leading to the same initial method of bugbattle.

**Comment by niklasfessler** [comment]
Ok it seems to work on our side. 

Do you have any wrappers around the app? Any other libraries? 
Hm. 

Do you know if all android apps have this bug?

**Comment by niklasfessler** [comment]
Thanks for you quick responses :)

**Comment by niklasfessler** [comment]
Can you tell me the defaultConfig from your android project. e.g. 

 defaultConfig {
        applicationId "bugbattle.io.bugbattle_android_sdk"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

**Comment by SudoPlz** [comment]
Hmm well we do use many libraries,

here's the full list:


```
"dependencies": {
    "@react-native-async-storage/async-storage": "1.15.5",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-firebase/app": "12.1.0",
    "@react-native-firebase/dynamic-links": "12.1.0",
    "@react-navigation/bottom-tabs": "5.11.11",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "5.14.5",
    "@sentry/react-native": "2.6.0",
    "axios": "0.21.1",
    "axios-auth-refresh": "3.1.0",
    "clone": "^2.1.2",
    "humps": "^2.0.1",
    "immer": "^6.0.1",
    "jsan": "^3.1.13",
    "lodash": "4.17.21",
    "moment-timezone": "0.5.33",
    "patch-package": "6.4.7",
    "postinstall-postinstall": "^2.1.0",
    "prop-types": "^15.7.2",
    "react": "17.0.2",
    "react-native": "0.64.2",
    "react-native-add-calendar-event": "4.0.0",
    "react-native-amplitude-analytics": "0.2.12",
    "react-native-bugbattle-sdk": "4.0.1",
    "react-native-camera": "3.44.1",
    "react-native-code-push": "7.0.1",
    "react-native-crypto-js": "^1.0.0",
    "react-native-device-info": "8.1.3",
    "react-native-gesture-handler": "1.10.3",
    "react-native-haptic-feedback": "1.11.0",
    "react-native-keychain": "7.0.0",
    "react-native-permissions": "3.0.4",
    "react-native-qrcode-scanner": "1.5.4",
    "react-native-reanimated": "1.7.1",
    "react-native-safe-area-context": "^0.7.2",
    "react-native-screens": "3.4.0",
    "react-native-tab-view": "2.13.0",
    "react-native-url-polyfill": "1.3.0",
    "react-native-vector-icons": "8.1.0",
    "react-native-webview": "11.6.4",
    "react-redux": "7.2.4",
    "react-timeout": "^1.2.0",
    "redux": "4.1.0",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "semver": "^7.3.5"
  },
```

I guess the only one that could be related may be the `react-navigation` library (main navigation library for almost all react-native projects) which uses `react-native-screens`.

> all android apps have this bug

no idea if other android apps are experiencing that, I only know about ours to be honest

**Comment by SudoPlz** [comment]
> Can you tell me the defaultConfig from your android project. e.g.
> 
> defaultConfig {
> applicationId "bugbattle.io.bugbattle_android_sdk"
> minSdkVersion 21
> targetSdkVersion 29
> versionCode 1
> versionName "1.0"
> testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
> }

Sure:
```
    defaultConfig {
        applicationId "com.acuityscheduling.client.android"
        minSdkVersion 21
        targetSdkVersion 29
        missingDimensionStrategy 'react-native-camera', 'general'
        multiDexEnabled true
    }
```

Other info:

```
        buildToolsVersion = "29.0.3"
        compileSdkVersion = 29
        ndkVersion = "20.1.5948944"
        androidXCore = "1.0.2"
```

**Comment by niklasfessler** [comment]
Thanks :) i can reproduce the bug and will work on a fix. It will take some time to fix and test.

**Comment by SudoPlz** [comment]
good job for reproducing this one.

Some feedback: I believe your otherwise great sdk and the product in general needs some crowdsourced Q/A.

**Comment by boehlerlukas** [comment]
@SudoPlz  Great input and something to focus on for the future! We have beta tester already in place but only in a limited amount. We will try to look for some crowed testing or a bigger beta pool for sure 😊

**Comment by niklasfessler** [comment]
Hey @SudoPlz,

we have released. Can you please check out the new version for react-native.

`npm i react-native-bugbattle-sdk@4.0.4`

Can you please confirm or deny if the bug is fixed so we can close the issue? 😀

Can you also confirm the other two issues? I will comment the version afterwards under the issues if it's fixed.

Greetings Niklas

**Comment by SudoPlz** [comment]
We now get the following issue:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.overridePendingTransition(int, int)' on a null object reference
    at bugbattle.io.bugbattle.ScreenshotTaker.openScreenshot(ScreenshotTaker.java:50)
    at bugbattle.io.bugbattle.ScreenshotTaker.takeScreenshot(ScreenshotTaker.java:34)
    at bugbattle.io.bugbattle.BBDetector.takeScreenshot(BBDetector.java:37)
    at bugbattle.io.bugbattle.ScreenshotGestureDetector.startBugReporting(ScreenshotGestureDetector.java:31)
    at bugbattle.io.bugbattle.ScreenshotGestureDetector.access$000(ScreenshotGestureDetector.java:9)
    at bugbattle.io.bugbattle.ScreenshotGestureDetector$1.onChange(ScreenshotGestureDetector.java:43)
    at android.database.ContentObserver.onChange(ContentObserver.java:130)
    at bugbattle.io.bugbattle.ScreenshotGestureDetector$1.onChange(ScreenshotGestureDetector.java:48)
    at android.database.ContentObserver.onChange(ContentObserver.java:145)
    at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by boehlerlukas** [comment]
@SudoPlz thanks for testing! @niklasfessler will have another look into the issue tomorrow.

**Comment by niklasfessler** [comment]
Hey @SudoPlz ,

Can you please check out the new version ? The bug should be fixed now.

Greetings Niklas

**Comment by SudoPlz** [comment]
@niklasfessler is that react-native-bugbattle-sdk 4.1.3?

**Comment by niklasfessler** [comment]
Yeah right :) This is the new version

**Comment by SudoPlz** [comment]
I haven't forgotten about this, we're a bit blocked on releasing the new version of our app, but as soon as we do it will definitely include 4.1.3.
As soon as that happens I'll update the issue and hopefully close it.

**Comment by niklasfessler** [comment]
ow no worries 😁 I did not want to stress you.
