### ISSUE TITLE
Invoking the in app feedback UI returns a blank page (Cannot GET /appwidget/)

### ISSUE THREAD

**Issue by SudoPlz** [BugBattle/Android-SDK#12]
![Screenshot_20210705-214658](https://user-images.githubusercontent.com/3070948/124509467-b2f5e300-ddda-11eb-9a6b-2c83534b8cdf.png)

"react-native-bugbattle-sdk": "4.0.1”,
"react-native": "0.64.2"

Google Pixel 2 XL
on a stable wifi

Also when this happened https://github.com/BugBattle/Android-SDK/issues/13 happened too.
https://github.com/BugBattle/Android-SDK/issues/13 doesn't ONLY happen when the https://github.com/BugBattle/Android-SDK/issues/12 happens, they are irrelevant, just mentioning it here.

**Comment by niklasfessler** [comment]
Hey :) sry havent seen it.

This will be fixed with the new version
