### ISSUE TITLE
Can't close the bugbattle UI

### ISSUE THREAD

**Issue by SudoPlz** [BugBattle/Android-SDK#13]
"react-native-bugbattle-sdk": "4.0.1”,
"react-native": "0.64.2"

Google Pixel 2 XL
on a stable wifi

Steps: 
1) I invoke bugbattle with screenshot invocation
2) left a [feature request](https://app.bugbattle.io/projects/5fdcfc203fdd1c0017591e7d/bugs/T1pe4L45lvPDQTqjA45yITKEVOPErTUs3GmEuGWTjaY42x6JOxcEOIptPHDLyOyaCLTsIp)
3) the bug battle UI didn't close (which I expected to happen after showing me a success message)
4) so I tried to close it myself by hitting the Close button

The screen momentarily closed, but then re-launched in milliseconds.
I can't go back to the app to use it because bugbattle UI keeps getting re-launched and won't go away.

**Comment by niklasfessler** [comment]
Thanks for your report. I will check this. 

Also released in the new version.
