### ISSUE TITLE
Installation instructions - code does not compile

### ISSUE THREAD

**Issue by jawinn** [BugBattle/Android-SDK#3]
Testing on Nexus 5X API 29 in Simulator. Target Android 10.0.

The provided instructions do not compile:
```
MainActivity.java:9: error: cannot find symbol
import bugbattle.io.bugbattle.BugBattleActivationMethod;
                             ^
  symbol:   class BugBattleActivationMethod
  location: package bugbattle.io.bugbattle
```

and 

```
error: incompatible types: MainActivity cannot be converted to Application
    BugBattle.initialise("ACTUALKEYHERE", BugBattleActivationMethod.SHAKE, this);
```

Based on autosuggestion in the editor, and looking up the error, I tried these which cause the build to be successful again. ~~But shake does not open BugBattle so I don't know if this is correct.~~ BugBattle **is** working on actual device now (shaking via simulator did not seem to work).
```
import bugbattle.io.bugbattle.BugBattle;
import bugbattle.io.bugbattle.controller.BugBattleActivationMethod;
```
and 
```
BugBattle.initialise("ACTUALKEYHERE", BugBattleActivationMethod.SHAKE, getApplication());
```

**Comment by niklasfessler** [comment]
Hey :) I gonna check that as soon as possible. On my side it looks fine.

Greetings niklas

jawinn <notifications@github.com> schrieb am Di., 5. Mai 2020, 18:08:

**Comment by jawinn** [comment]
Great, thank you.
FYI your [support documentation](https://developers.bugbattle.io/) site appears to be 404 right now; I was trying to find some way to contact you.

**Comment by jawinn** [comment]
Note, it is working on an actual Android phone, with those changes I documented (shaking in the simulator just didn't seem to want to work).

**Comment by niklasfessler** [comment]
Hm ok 👍 Thank you. We gonna rework the whole project starting in June to get a more reliable setup.

**Comment by niklasfessler** [comment]
Ive updated the Readme file :) thanks for you feedback
