### ISSUE TITLE
BugBattle doesn't get invoked by shake gesture on some android devices

### ISSUE THREAD

**Issue by up-ayudkin** [BugBattle/Android-SDK#5]
On some android devices, shake gesture doesn't open BugBattle.
The reason for that is because under the hood "ACCELEROMETER_UNCALIBRATED" is used to detect gestures (instead of regular "ACCELEROMETER"). Uncalibrated accelerometer isn't exposed on some devices which makes shake gestures un recognisable.

The appropriate piece of code (in ShakeGestureDetector.java):
`        mAccelerometer = mSensorManager
                .getDefaultSensor(Sensor.TYPE_ACCELEROMETER_UNCALIBRATED);`

**Comment by boehlerlukas** [comment]
Hey @up-ayudkin ! Thanks for your bug report.

@niklasfessler will take care of the issue asap.

Best regards,
Lukas

**Comment by niklasfessler** [comment]
Hey up-ayudkin,

thanks for your bug report. I´ve fixed the bug. Please use the following version:

3.0.33

Please confirm the change so we can close the bug report :) 

Greetings Niklas

**Comment by niklasfessler** [comment]
No answer from user.
