### ISSUE TITLE
app_name used in the SDK can clash with name used in target app

### ISSUE THREAD

**Issue by maciejpigulski** [BugBattle/Android-SDK#7]
In my app we are using `app_name` string resource name to provide name for the application. In the SDK same name is used and it is messing up with my application name and instead of having my name I see 'bugbattle' in the launcher. It might be a broader issue given that Android Studio by default when creating new application is using `app_name` as the key for application name.

Of course I can do some work on my end to mitigate that and use some manifest overrides but to find the cause of this took me something like 2 hours and it is an udocumented thing. Also this is an SDK that really doesn't have a name, name has to be provided for the Android framework sake to compile the SDK. I guess if you would replace the key `app_name` with something like `bugbattle_name` or something else that has very little chance of being a name clash would be much easier for developers.

Thanks.

<img width="1030" alt="Screenshot 2021-03-01 at 12 09 24" src="https://user-images.githubusercontent.com/7657893/109490640-cc7fca80-7a88-11eb-94fb-5fad9737d5f8.png">

![Screenshot_1614597329](https://user-images.githubusercontent.com/7657893/109490703-e3262180-7a88-11eb-91e6-ffcb0d9b656d.png)

**Comment by niklasfessler** [comment]
Hey. Ow sry for that. I gonna quick fix that. Give me 5 minutes to do that. 

Thanks for your feedback.

Greetings Niklas

**Comment by niklasfessler** [comment]
Hey @maciejpigulski,

i've changed the app_name property of bugbattle to another key. Upgrade Bugbattle to 3.1.7 and it is fixed. Sry for the inconvenience caused.

Please confirm that the bug is fixed so we can close the issue 😄 

Greetings Niklas

**Comment by maciejpigulski** [comment]
Looks like its fixed. Thanks for the prompt fix!

**Comment by niklasfessler** [comment]
Thank you for using Bugbattle :)
