### ISSUE TITLE
app_name Resource in Library Overrides Other Modules

### ISSUE THREAD

**Issue by StuStirling** [BugBattle/Android-SDK#8]
In the SDK's module under `strings.xml` is a value called `app_name`.

This is used by a lot of apps and leaving it in this library unnecessarily conflicts with modules that depend on it.

 Its only used in the `AndroidManifest.xml`. Its rename to something else would resolve any conflicts.

**Comment by StuStirling** [comment]
Seeing this on version 1.3.5. Upgrading to 1.3.8 or downgrading to 1.3.0 resolves it

**Comment by boehlerlukas** [comment]
@StuStirling that was an issue on our part. As you already found out yourself (you were too fast for us to respond 😊), the latest version already solves it. I will close the issue for now.
